---
- name: Install Docker on Amazon Linux 2023
  hosts: webserver
  become: yes

  tasks:
    - name: Install growpart package
      dnf:
        name: cloud-utils-growpart
        state: present

    - name: Expand partition
      shell: "growpart /dev/nvme0n1 1"
      ignore_errors: yes

    - name: Expand XFS filesystem
      shell: "xfs_growfs /"
      ignore_errors: yes

    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Restart Docker to apply group membership changes
      service:
        name: docker
        state: restarted